### ISSUE TITLE
URL in project description doesn't exist

### ISSUE THREAD

**Issue by darylf** [vidbina/landing-strip#1]
The URL in this project's description returns a 404. 

http://vidbina.github.io/landing-strip/

I guess this project needs its own *landing strip*? :smile:

**Comment by vidbina** [comment]
yes it does... getting it setup :P

**Comment by vidbina** [comment]
@darylf thanks for pointing it out... I've fixed it. If you have any ideas of pages that I could add to the list, feel free to create an issue for them or submit a PR.
